#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build Basis Sentiment outputs from Massive CME futures plus existing legs.

The current repository already contains physical prices, COT scores, narrative
events, and older hand-merged Basis Sentiment samples. This script makes that
fusion reproducible once the CME futures leg is generated by:

    python Data_light_version/CME/massive_cme_futures_fetcher.py

It does not call external APIs. It reads checked-in/local normalized files and
writes a new detailed basis sentiment artifact.
"""

from __future__ import annotations

import argparse
import csv
import json
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple


DEFAULT_MAX_ACCEPTED_PHYSICAL_LAG_DAYS = 14
SOYBEAN_BUSHEL_WEIGHT_LB = 60.0
SHORT_TON_LB = 2000.0


EIA_SOURCE_DETAILS = {
    "WTI_CRUDE": {
        "source_family": "EIA",
        "source_id": "EIA_WTI_DAILY",
        "source_series": "PET.RWTC.D",
        "instrument": "WTI_CRUDE",
        "delivery_point": "CUSHING_OK",
        "data_type": "SPOT_PRICE",
        "unit": "USD_PER_BBL",
        "raw_source_url": "https://www.eia.gov/dnav/pet/hist/RWTCD.htm",
        "mapping_status": "STRICT",
        "notes": "WTI Cushing spot price from latest available EIA daily observation.",
    },
    "HENRY_HUB_NG": {
        "source_family": "EIA",
        "source_id": "EIA_HENRY_HUB_DAILY",
        "source_series": "NG.RNGWHHD.D",
        "instrument": "HENRY_HUB_NG",
        "delivery_point": "HENRY_HUB_LA",
        "data_type": "SPOT_PRICE",
        "unit": "USD_PER_MMBTU",
        "raw_source_url": "https://www.eia.gov/dnav/ng/hist/RNGWHHDD.htm",
        "mapping_status": "STRICT",
        "notes": "Henry Hub spot price from latest available EIA daily observation.",
    },
}


BASIS_MAPPINGS = {
    "CL": [
        {
            "physical_source_family": "EIA",
            "physical_series_key": "WTI_CRUDE",
            "basis_label": "CL_WTI_CUSHING",
        }
    ],
    "NG": [
        {
            "physical_source_family": "EIA",
            "physical_series_key": "HENRY_HUB_NG",
            "basis_label": "NG_HENRY_HUB",
        }
    ],
    "ZC": [
        {
            "physical_source_family": "USDA_AMS",
            "physical_series_key": "CORN_DECATUR_PROXY",
            "basis_label": "ZC_CORN_DECATUR_PROXY",
        },
        {
            "physical_source_family": "USDA_AMS",
            "physical_series_key": "CORN_GULF_PROXY",
            "basis_label": "ZC_CORN_GULF_PROXY",
        },
        {
            "physical_source_family": "USDA_AMS",
            "physical_series_key": "CORN_COUNTRY_ELEVATOR_OK_FALLBACK",
            "basis_label": "ZC_CORN_OK_FALLBACK",
        },
    ],
    "ZS": [
        {
            "physical_source_family": "USDA_AMS",
            "physical_series_key": "SOYBEAN_MEAL",
            "basis_label": "ZS_SOYBEAN_MEAL_RELATED_PROXY",
            "related_proxy": True,
        }
    ],
    "ZW": [
        {
            "physical_source_family": "USDA_AMS",
            "physical_series_key": "SRW_WHEAT",
            "basis_label": "ZW_SRW_WHEAT",
        }
    ],
    "GC": [],
    "SI": [],
}


PREFERRED_CSV_FIELDS = [
    "trade_date",
    "symbol",
    "basis_label",
    "instrument",
    "commodity_label",
    "exchange",
    "futures_contract",
    "is_front_month",
    "futures_settlement_raw",
    "futures_price_unit",
    "futures_settlement_common",
    "basis_common_unit",
    "front_next_spread_common",
    "term_structure_signal",
    "volume",
    "transactions",
    "physical_component_role",
    "physical_source_family",
    "physical_series_key",
    "physical_source_id",
    "physical_instrument",
    "physical_delivery_point",
    "physical_price_asof",
    "physical_price_asof_date",
    "physical_unit",
    "physical_mapping_status",
    "physical_lag_days",
    "physical_notes",
    "physical_raw_source_url",
    "physical_tos_status",
    "physical_gatekeeper_cleared",
    "physical_price_converted",
    "physical_conversion_formula",
    "futures_settlement_converted",
    "futures_conversion_formula",
    "basis_value_asof",
    "basis_formula_asof",
    "basis_ready",
    "basis_value_asof_status",
    "basis_quality_flag",
    "basis_calculation_input_status",
    "conversion_note",
    "cot_score",
    "cot_signal",
    "cot_confidence",
    "cot_report_date",
    "cot_lag_days",
    "cot_score_status",
    "cot_summary",
    "narrative_event_count",
    "narrative_bullish_count",
    "narrative_bearish_count",
    "narrative_neutral_count",
    "narrative_unknown_count",
    "narrative_avg_sentiment_score",
    "narrative_avg_confidence_score",
    "narrative_aggregate_direction",
    "narrative_latest_event_timestamp",
    "narrative_lag_days",
    "narrative_top_event_headline",
    "narrative_tos_status",
    "narrative_gatekeeper_cleared",
    "available_components",
    "missing_components",
    "merged_at_utc",
]


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def save_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def write_csv(path: Path, rows: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    keys = list(PREFERRED_CSV_FIELDS)
    for row in rows:
        for key in row:
            if key not in keys:
                keys.append(key)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=keys)
        writer.writeheader()
        for row in rows:
            out = {}
            for key in keys:
                value = row.get(key)
                out[key] = json.dumps(value, ensure_ascii=False) if isinstance(value, (dict, list)) else value
            writer.writerow(out)


def parse_dt(value: Any) -> Optional[datetime]:
    if value in (None, ""):
        return None
    text = str(value).strip()
    for fmt in ("%Y-%m-%dT%H:%M:%S%z", "%Y-%m-%dT%H:%M:%S+00:00", "%Y-%m-%d", "%m/%d/%Y"):
        try:
            if fmt == "%Y-%m-%dT%H:%M:%S%z":
                return datetime.fromisoformat(text.replace("Z", "+00:00"))
            return datetime.strptime(text[:10] if fmt == "%Y-%m-%d" else text, fmt)
        except Exception:
            pass
    return None


def day_diff(later: Any, earlier: Any) -> Optional[int]:
    later_dt = parse_dt(later)
    earlier_dt = parse_dt(earlier)
    if not later_dt or not earlier_dt:
        return None
    return (later_dt.date() - earlier_dt.date()).days


def safe_float(value: Any) -> Optional[float]:
    if value in (None, ""):
        return None
    try:
        return float(value)
    except Exception:
        return None


def load_cme_records(path: Path) -> List[Dict[str, Any]]:
    payload = load_json(path)
    return payload.get("records", []) if isinstance(payload, dict) else []


def latest_front_by_symbol(records: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    out: Dict[str, Dict[str, Any]] = {}
    for row in records:
        if not row.get("is_front_month"):
            continue
        symbol = row.get("symbol")
        if not symbol or not row.get("trade_date"):
            continue
        current = out.get(symbol)
        if current is None or str(row["trade_date"]) > str(current.get("trade_date")):
            out[symbol] = row
    return out


def curve_context(records: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    by_symbol_date: Dict[Tuple[str, str], List[Dict[str, Any]]] = {}
    for row in records:
        symbol = row.get("symbol")
        trade_date = row.get("trade_date")
        if not symbol or not trade_date:
            continue
        by_symbol_date.setdefault((symbol, trade_date), []).append(row)

    out: Dict[str, Dict[str, Any]] = {}
    for (symbol, trade_date), rows in by_symbol_date.items():
        rows = sorted(rows, key=lambda item: int(item.get("contract_rank") or 999))
        front = next((item for item in rows if item.get("contract_rank") == 1), None)
        second = next((item for item in rows if item.get("contract_rank") == 2), None)
        if not front:
            continue
        spread = None
        signal = "not_available"
        if second:
            front_value = safe_float(front.get("settlement_common_unit_value"))
            second_value = safe_float(second.get("settlement_common_unit_value"))
            if front_value is not None and second_value is not None:
                spread = round(second_value - front_value, 8)
                if spread > 0:
                    signal = "contango"
                elif spread < 0:
                    signal = "backwardation"
                else:
                    signal = "flat"
        current = out.get(symbol)
        if current is None or trade_date > current["trade_date"]:
            out[symbol] = {
                "trade_date": trade_date,
                "front_next_spread_common": spread,
                "term_structure_signal": signal,
                "second_contract": second.get("futures_contract") if second else None,
            }
    return out


def load_eia_latest(path: Path) -> Dict[str, Dict[str, Any]]:
    payload = load_json(path)
    out = {}
    for group in payload.get("group_results", []):
        series_key = group.get("series_key")
        if not series_key:
            continue
        details = dict(EIA_SOURCE_DETAILS.get(series_key, {}))
        details.update(
            {
                "series_key": series_key,
                "timestamp": group.get("latest_timestamp"),
                "value": group.get("latest_value"),
                "tos_status": "GO",
                "gatekeeper_cleared": True,
            }
        )
        out[series_key] = details
    return out


def load_usda_latest(path: Path) -> Dict[str, Dict[str, Any]]:
    payload = load_json(path)
    records = payload.get("records", []) if isinstance(payload, dict) else []
    out: Dict[str, Dict[str, Any]] = {}
    for row in records:
        key = row.get("series_key")
        if not key:
            continue
        current = out.get(key)
        if current is None or (parse_dt(row.get("timestamp")) or datetime.min) > (parse_dt(current.get("timestamp")) or datetime.min):
            out[key] = row
    return out


def load_latest_cot(path: Path) -> Dict[str, Dict[str, Any]]:
    payload = load_json(path)
    out: Dict[str, Dict[str, Any]] = {}
    for row in payload.get("records", []):
        symbol = row.get("instrument")
        if not symbol:
            continue
        current = out.get(symbol)
        if current is None or str(row.get("report_date") or "") > str(current.get("report_date") or ""):
            out[symbol] = row
    return out


def direction_score(direction: Any) -> float:
    value = str(direction or "").upper()
    if value == "BULLISH":
        return 1.0
    if value == "BEARISH":
        return -1.0
    if value == "MIXED":
        return 0.0
    return 0.0


def load_narrative_summary(path: Path) -> Dict[str, Dict[str, Any]]:
    payload = load_json(path)
    records = payload.get("records", []) if isinstance(payload, dict) else []
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for row in records:
        target = row.get("target_commodity") or row.get("primary_commodity")
        if target:
            grouped.setdefault(str(target), []).append(row)

    out = {}
    for symbol, rows in grouped.items():
        count = len(rows)
        if not count:
            continue
        latest = max(rows, key=lambda item: str(item.get("timestamp") or ""))
        confidence_values = [safe_float(item.get("confidence_score")) for item in rows]
        confidence_values = [value for value in confidence_values if value is not None]
        sentiment_values = [direction_score(item.get("direction")) * (safe_float(item.get("confidence_score")) or 0.0) for item in rows]
        avg_sentiment = sum(sentiment_values) / count if count else 0.0
        avg_confidence = sum(confidence_values) / len(confidence_values) if confidence_values else None
        bullish = sum(1 for item in rows if str(item.get("direction") or "").upper() == "BULLISH")
        bearish = sum(1 for item in rows if str(item.get("direction") or "").upper() == "BEARISH")
        neutral = sum(1 for item in rows if str(item.get("direction") or "").upper() == "NEUTRAL")
        unknown = sum(1 for item in rows if str(item.get("direction") or "").upper() == "UNKNOWN")
        if avg_sentiment >= 0.25:
            aggregate_direction = "bullish"
        elif avg_sentiment <= -0.25:
            aggregate_direction = "bearish"
        elif avg_sentiment > 0.05:
            aggregate_direction = "mildly_bullish"
        elif avg_sentiment < -0.05:
            aggregate_direction = "mildly_bearish"
        else:
            aggregate_direction = "neutral"
        out[symbol] = {
            "event_count": count,
            "bullish_count": bullish,
            "bearish_count": bearish,
            "neutral_count": neutral,
            "unknown_count": unknown,
            "avg_sentiment_score": round(avg_sentiment, 6),
            "avg_confidence_score": round(avg_confidence, 6) if avg_confidence is not None else None,
            "aggregate_direction": aggregate_direction,
            "latest_event_timestamp": latest.get("timestamp"),
            "top_event_headline": latest.get("headline_paraphrase") or latest.get("headline_original"),
            "tos_status": "GO_WITH_SOURCE_SPECIFIC_TOS",
            "gatekeeper_cleared": all(bool(item.get("gatekeeper_cleared")) for item in rows),
        }
    return out


def physical_record(mapping: Dict[str, Any], eia: Dict[str, Dict[str, Any]], usda: Dict[str, Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    family = mapping["physical_source_family"]
    key = mapping["physical_series_key"]
    if family == "EIA":
        return eia.get(key)
    if family == "USDA_AMS":
        return usda.get(key)
    return None


def normalize_physical_fields(record: Dict[str, Any], mapping: Dict[str, Any]) -> Dict[str, Any]:
    family = mapping["physical_source_family"]
    if family == "EIA":
        return {
            "physical_source_family": family,
            "physical_series_key": record.get("series_key"),
            "physical_source_id": record.get("source_id"),
            "physical_source_series": record.get("source_series"),
            "physical_instrument": record.get("instrument"),
            "physical_delivery_point": record.get("delivery_point"),
            "physical_data_type": record.get("data_type"),
            "physical_price_asof": safe_float(record.get("value")),
            "physical_price_asof_date": record.get("timestamp"),
            "physical_unit": record.get("unit"),
            "physical_mapping_status": record.get("mapping_status"),
            "physical_notes": record.get("notes"),
            "physical_raw_source_url": record.get("raw_source_url"),
            "physical_tos_status": record.get("tos_status"),
            "physical_gatekeeper_cleared": record.get("gatekeeper_cleared"),
        }
    return {
        "physical_source_family": family,
        "physical_series_key": record.get("series_key"),
        "physical_source_id": record.get("source_id"),
        "physical_source_series": record.get("slug_id"),
        "physical_instrument": record.get("instrument"),
        "physical_delivery_point": record.get("delivery_point"),
        "physical_data_type": record.get("data_type"),
        "physical_price_asof": safe_float(record.get("value")),
        "physical_price_asof_date": record.get("timestamp"),
        "physical_unit": record.get("unit"),
        "physical_mapping_status": record.get("source_mapping_status"),
        "physical_notes": record.get("proxy_reason"),
        "physical_raw_source_url": record.get("raw_source_url"),
        "physical_tos_status": record.get("tos_status"),
        "physical_gatekeeper_cleared": record.get("gatekeeper_cleared"),
    }


def convert_for_basis(symbol: str, physical: Dict[str, Any], future: Dict[str, Any]) -> Dict[str, Any]:
    physical_value = safe_float(physical.get("physical_price_asof"))
    futures_value = safe_float(future.get("settlement_common_unit_value"))
    futures_unit = future.get("common_unit")
    physical_unit = physical.get("physical_unit")

    if symbol == "ZS" and physical.get("physical_series_key") == "SOYBEAN_MEAL":
        converted_futures = None if futures_value is None else round(futures_value * (SHORT_TON_LB / SOYBEAN_BUSHEL_WEIGHT_LB), 6)
        return {
            "basis_common_unit": "USD_PER_SHORT_TON",
            "physical_price_converted": physical_value,
            "physical_conversion_formula": "no_conversion_needed; USDA soybean meal physical is already USD_PER_SHORT_TON",
            "futures_settlement_converted": converted_futures,
            "futures_conversion_formula": "ZS futures USD_PER_BUSHEL * (2000 lb per short ton / 60 lb per soybean bushel)",
            "conversion_note": "Related proxy: soybean meal physical is compared with soybean futures converted to USD_PER_SHORT_TON; not a strict raw-soybean cash basis.",
        }

    if physical_unit == futures_unit:
        return {
            "basis_common_unit": physical_unit,
            "physical_price_converted": physical_value,
            "physical_conversion_formula": "no_conversion_needed",
            "futures_settlement_converted": futures_value,
            "futures_conversion_formula": future.get("unit_conversion"),
            "conversion_note": f"Physical and futures legs are both in {physical_unit}.",
        }

    return {
        "basis_common_unit": None,
        "physical_price_converted": physical_value,
        "physical_conversion_formula": "unsupported_conversion",
        "futures_settlement_converted": futures_value,
        "futures_conversion_formula": future.get("unit_conversion"),
        "conversion_note": f"Unsupported unit pairing: physical={physical_unit}, futures={futures_unit}.",
    }


def basis_quality(trade_date: Any, physical_date: Any, max_lag_days: int) -> Tuple[Optional[int], str, str]:
    lag = day_diff(trade_date, physical_date)
    if lag is None:
        return None, "PHYSICAL_DATE_UNKNOWN", "INCOMPLETE_MISSING_PHYSICAL_DATE"
    if lag == 0:
        return lag, "EXACT_DATE_PHYSICAL", "COMPLETE_EXACT_DATE_PHYSICAL"
    if 0 < lag <= max_lag_days:
        return lag, f"ASOF_PHYSICAL_ACCEPTED_LAG_{lag}D", "COMPLETE_WITH_LATEST_AVAILABLE_ASOF_PHYSICAL"
    if lag > max_lag_days:
        return lag, f"STALE_PHYSICAL_LAG_{lag}D_REVIEW", "COMPLETE_WITH_STALE_PHYSICAL_REVIEW"
    return lag, "PHYSICAL_DATE_AFTER_FUTURES_REVIEW", "COMPLETE_WITH_DATE_ALIGNMENT_REVIEW"


def build_row(
    symbol: str,
    future: Dict[str, Any],
    mapping: Optional[Dict[str, Any]],
    physical_source: Optional[Dict[str, Any]],
    cot: Optional[Dict[str, Any]],
    narrative: Optional[Dict[str, Any]],
    curve: Optional[Dict[str, Any]],
    max_lag_days: int,
) -> Dict[str, Any]:
    available = ["cme_futures_settlement"]
    missing = []
    row = {
        "trade_date": future.get("trade_date"),
        "symbol": symbol,
        "basis_label": mapping.get("basis_label") if mapping else f"{symbol}_FUTURES_ONLY",
        "instrument": future.get("instrument"),
        "commodity_label": future.get("commodity_label"),
        "exchange": future.get("exchange"),
        "futures_contract": future.get("futures_contract"),
        "is_front_month": future.get("is_front_month"),
        "futures_settlement_raw": future.get("settlement_price"),
        "futures_price_unit": future.get("price_unit"),
        "futures_settlement_common": future.get("settlement_common_unit_value"),
        "volume": future.get("volume"),
        "transactions": future.get("transactions"),
        "front_next_spread_common": curve.get("front_next_spread_common") if curve else None,
        "term_structure_signal": curve.get("term_structure_signal") if curve else None,
        "merged_at_utc": utc_now(),
    }

    if curve and curve.get("front_next_spread_common") is not None:
        available.append("term_structure")

    if physical_source and mapping:
        physical = normalize_physical_fields(physical_source, mapping)
        row.update(physical)
        row["physical_component_role"] = "PHYSICAL_PRICE_LATEST_AVAILABLE_ASOF"
        conversion = convert_for_basis(symbol, physical, future)
        row.update(conversion)
        lag, quality_flag, input_status = basis_quality(row.get("trade_date"), row.get("physical_price_asof_date"), max_lag_days)
        row["physical_lag_days"] = lag
        physical_converted = safe_float(row.get("physical_price_converted"))
        futures_converted = safe_float(row.get("futures_settlement_converted"))
        basis_ready = physical_converted is not None and futures_converted is not None and row.get("basis_common_unit") is not None
        row["basis_ready"] = basis_ready
        if basis_ready:
            row["basis_value_asof"] = round(physical_converted - futures_converted, 6)
            row["basis_value_asof_status"] = "CALCULATED_WITH_LATEST_AVAILABLE_ASOF_PHYSICAL"
            row["basis_formula_asof"] = "physical_price_asof - front_month_futures_settlement"
            available.append("physical_latest_available_asof")
        else:
            row["basis_value_asof"] = None
            row["basis_value_asof_status"] = "NOT_CALCULATED_UNIT_OR_VALUE_MISSING"
            row["basis_formula_asof"] = None
            missing.append("basis_conversion")
        row["basis_quality_flag"] = quality_flag
        row["basis_calculation_input_status"] = input_status
    else:
        row.update(
            {
                "physical_component_role": "NO_PHYSICAL_MAPPING_AVAILABLE",
                "basis_ready": False,
                "basis_value_asof": None,
                "basis_value_asof_status": "NOT_CALCULATED_NO_PHYSICAL_MAPPING",
                "basis_quality_flag": "NO_PHYSICAL_MAPPING_AVAILABLE",
                "basis_calculation_input_status": "INCOMPLETE_NO_PHYSICAL_MAPPING",
            }
        )
        missing.append("physical_price")

    if cot:
        available.append("cot_overlay")
        row.update(
            {
                "cot_score": cot.get("cot_score"),
                "cot_signal": cot.get("cot_signal"),
                "cot_confidence": cot.get("confidence"),
                "cot_report_date": cot.get("report_date"),
                "cot_lag_days": day_diff(row.get("trade_date"), cot.get("report_date")),
                "cot_score_status": cot.get("score_status"),
                "cot_summary": cot.get("summary"),
            }
        )
    else:
        missing.append("cot_overlay")

    if narrative:
        available.append("narrative_sentiment")
        row.update(
            {
                "narrative_event_count": narrative.get("event_count"),
                "narrative_bullish_count": narrative.get("bullish_count"),
                "narrative_bearish_count": narrative.get("bearish_count"),
                "narrative_neutral_count": narrative.get("neutral_count"),
                "narrative_unknown_count": narrative.get("unknown_count"),
                "narrative_avg_sentiment_score": narrative.get("avg_sentiment_score"),
                "narrative_avg_confidence_score": narrative.get("avg_confidence_score"),
                "narrative_aggregate_direction": narrative.get("aggregate_direction"),
                "narrative_latest_event_timestamp": narrative.get("latest_event_timestamp"),
                "narrative_lag_days": day_diff(row.get("trade_date"), narrative.get("latest_event_timestamp")),
                "narrative_top_event_headline": narrative.get("top_event_headline"),
                "narrative_tos_status": narrative.get("tos_status"),
                "narrative_gatekeeper_cleared": narrative.get("gatekeeper_cleared"),
            }
        )
    else:
        missing.append("narrative_sentiment")

    row["available_components"] = ";".join(available)
    row["missing_components"] = ";".join(missing)
    return row


def validate_output(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    basis_rows = [row for row in rows if row.get("basis_ready")]
    stale_rows = [row for row in rows if str(row.get("basis_quality_flag") or "").startswith("STALE_")]
    futures_only_rows = [row for row in rows if row.get("physical_component_role") == "NO_PHYSICAL_MAPPING_AVAILABLE"]
    errors = []
    if not rows:
        errors.append("No basis sentiment rows were generated.")
    if not basis_rows:
        errors.append("No basis-ready rows were generated.")
    return {
        "validated_at": utc_now(),
        "stage": "basis_sentiment_from_massive_cme",
        "all_required_ok": not errors,
        "record_count": len(rows),
        "basis_ready_count": len(basis_rows),
        "stale_physical_review_count": len(stale_rows),
        "futures_only_count": len(futures_only_rows),
        "symbols": sorted({row.get("symbol") for row in rows if row.get("symbol")}),
        "basis_labels": [row.get("basis_label") for row in rows],
        "errors": errors,
        "warnings": [
            "Rows with STALE_PHYSICAL_* flags are calculated but should be reviewed before publication.",
            "ZS uses soybean meal as a related physical proxy, matching the existing repository sample logic.",
            "GC and SI are emitted as futures-only rows because no physical basis leg is present in the current public subset.",
        ],
    }


def parse_args() -> argparse.Namespace:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cme-json", type=Path, default=repo_root / "Data_light_version/CME/massive_cme_futures_normalized.json")
    parser.add_argument("--eia-validation", type=Path, default=repo_root / "Data_light_version/EIA/eia_normalization_validation_report.json")
    parser.add_argument("--usda-json", type=Path, default=repo_root / "Data_light_version/USDA/usda_grain_physical_prices_normalized.json")
    parser.add_argument("--cot-json", type=Path, default=repo_root / "COT_scoring_positioning/cftc_cot_scores.json")
    parser.add_argument("--narrative-json", type=Path, default=repo_root / "Data_light_version/Reuters/narrative_events_normalized.json")
    parser.add_argument("--out-dir", type=Path, default=repo_root / "Basis_sentiment")
    parser.add_argument("--max-accepted-physical-lag-days", type=int, default=DEFAULT_MAX_ACCEPTED_PHYSICAL_LAG_DAYS)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    cme_records = load_cme_records(args.cme_json)
    latest_futures = latest_front_by_symbol(cme_records)
    curve = curve_context(cme_records)
    eia = load_eia_latest(args.eia_validation)
    usda = load_usda_latest(args.usda_json)
    cot = load_latest_cot(args.cot_json)
    narrative = load_narrative_summary(args.narrative_json)

    rows: List[Dict[str, Any]] = []
    for symbol in sorted(latest_futures):
        future = latest_futures[symbol]
        mappings = BASIS_MAPPINGS.get(symbol, [])
        if not mappings:
            rows.append(
                build_row(
                    symbol,
                    future,
                    None,
                    None,
                    cot.get(symbol),
                    narrative.get(symbol),
                    curve.get(symbol),
                    args.max_accepted_physical_lag_days,
                )
            )
            continue
        for mapping in mappings:
            rows.append(
                build_row(
                    symbol,
                    future,
                    mapping,
                    physical_record(mapping, eia, usda),
                    cot.get(symbol),
                    narrative.get(symbol),
                    curve.get(symbol),
                    args.max_accepted_physical_lag_days,
                )
            )

    rows.sort(key=lambda row: (row.get("symbol") or "", row.get("basis_label") or ""))
    payload = {
        "generated_at": utc_now(),
        "source": "BASIS_SENTIMENT_FROM_MASSIVE_CME",
        "stage": "futures_physical_cot_narrative_merge",
        "records": rows,
    }
    validation = validate_output(rows)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    save_json(args.out_dir / "basis_sentiment_from_massive_cme.json", payload)
    write_csv(args.out_dir / "basis_sentiment_from_massive_cme.csv", rows)
    save_json(args.out_dir / "basis_sentiment_from_massive_cme_validation_report.json", validation)
    print(f"records={len(rows)}")
    print(f"basis_ready_count={validation['basis_ready_count']}")
    print(f"validation_ok={validation['all_required_ok']}")
    return 0 if validation["all_required_ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
